# Use an official Python runtime as the base image
FROM python:3.9-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the local application code into the container
COPY . .

# Install dependencies
RUN pip install -r requirements.txt