version: "3.9"
services:

  session:
    build: .
    image: app/session:latest
    command: python3 events/session.py
    env_file: .env

  signup:
    build: .
    image: app/signup:latest
    command: python3 events/signup.py
    env_file: .env
