version: "3.9"
services:

  session:
    build: .
    image: app/session:latest
    command: python3 events/create_sessions.py
    env_file: .env

  signup:
    build: .
    image: app/signup:latest
    command: python3 events/create_signups.py
    env_file: .env
